service: asg-ecr
provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: shared
  stackTags:
    ManagedBy: "braulio.megias@asg.com"
    CreatedBy: "bharat.nainani@asg.com"
    Name: asg-registry-lifecycle-policy
    Project: product-distribution

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    - Effect: Allow
      Action:
        - ecr:*
      Resource: "*"

functions:
  lifecycle-policy:
    handler: main.lambda_handler
    description: "Image Clean Up Policy"
    memorySize: 150
    timeout: 30
    runtime: python3.8
    events:
      - cloudwatchEvent:
          name: 'ecr-lifecycle-cw-event'
          description: 'Cloudwatch event to trigger lifcycle policy whenever image is pushed in ECR'
          event:
            source: 
             - 'aws.ecr'
            detail-type: 
             - 'ECR Image Action'
            detail:
              action-type: 
               - 'PUSH'
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    pythonBin: python3
    dockerizePip: non-linux
